<?php

declare(strict_types=1);

/**
 * @file
 * Primary module hooks for villaagency module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Prepares variables for views-style-best-deal.html.twig template.
 */
function template_preprocess_views_style_best_deal(array &$variables): void {
  $view = $variables['view'];
  $options = $view->style_plugin->options;

  $variables['default_row_class'] = $options['default_row_class'];
  foreach ($variables['rows'] as $id => $row) {
    $variables['rows'][$id] = [
      'content' => $row,
      'attributes' => new Attribute(),
    ];
    if ($row_class = $view->style_plugin->getRowClass($id)) {
      $variables['rows'][$id]['attributes']->addClass($row_class);
    }
  }
}
